#!/bin/sh

setxkbmap -option "caps:swapescape"
xbindkeys -f $HOME/dotfiles/xbindkeys
xrdb -merge $HOME/.Xresources
feh --bg-fill --randomize --no-fehbg ~/media/pictures/wallpaper/* &
flameshot &
dunst &
picom &
clipmenud &
dwm

