#!/bin/bash

[ "$(stat -c %y ~/.cache/corona) | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')"  ] &&
	curl -s https://corona-stats.online/co > ~/.cache/corona


grep "Colombia" ~/.cache/corona |
          sed "s/\s*//g  ; s/║//g ; s/│/;/g" |
          awk -F';' '{print "Corona=> Total: " $3 " (New: " $4") Dead: " $5 ""}'
