#!/bin/bash

[ "$(stat -c %y ~/.cache/corona) 2>&1 | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')"  ] &&
	curl -s https://corona-stats.online/co | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g" > ~/.cache/corona


grep "Colombia" ~/.cache/corona |
          sed "s/\s*//g  ; s/║//g ; s/│/;/g" |
          awk -F';' '{print "Total: " $3 " (New: " $4") Dead: " $5 ""}'
