#!/bin/sh

amazon_dock_hdmi='DVI-I-1-1'
laptop_screen='eDP1'
hdmi_screen='HDMI1'


# Using a lot of what luke smith did, but changed it around for my own purposes.

onescreen() { # If only one output available or chosen.
	xrandr --output $1 --auto --output $2 --off
	}

onescreen_dock(){
	xrandr --output $1 --auto --output $2 --off
}
# Get all possible displays
allposs=$(xrandr -q | grep "connected")

# Get all connected screens.
screens=$(echo "$allposs" | awk '/ connected/ {print $1}')

twoscreens() {
#two screens not mirroring
  xrandr --output $hdmi_screen --auto --output $laptop_screen --auto --right-of $hdmi_screen
}

twomirroredscreens() {
#Two screens mirrored
  xrandr --output HDMI1 --auto --output eDP1 --auto
}


# Get user choice including multi-monitor and manual selection:
chosen=$(printf "External Monitor\\nLaptop Display\\nTwo Monitors\\nMirrored\\nAmazon Dock" "$screens" | dmenu -i -p "Select Display Option:") &&

if [ "$chosen" == "External Monitor" ]; then
       	onescreen "HDMI1" "eDP1"
elif [ "$chosen" == "Laptop Display" ]; then
       	onescreen  "eDP1" "HDMI1"
elif [ "$chosen" == "Two Monitors" ]; then
  twoscreens
elif [ "$chosen" == "Amazon Dock" ]; then
    xrandr --output eDP1 --auto --primary --output DVI-I-1-1 --auto --same-as eDP1
else
  twomirroredscreens
fi

# to use witht the amazon dock
#xrandr --output eDP1 --auto --primary --output DVI-I-1-1 --auto --same-as eDP1
