#!/bin/sh

echo -e "What do you want to do? \n\nNuke: Destroy everything \nLite: Destroy containers\n"

select answer in "Nuke" "Lite"; do
	case $answer in
		Nuke ) docker stop $(docker ps -a -q) 2>/dev/null; docker container prune -f;  docker rmi $(docker images -q) -f 2>/dev/null; docker info 2>/dev/null | grep --after-context=3 "Containers"; break;;
		Lite ) docker stop $(docker ps -a -q) 2>/dev/null; docker container prune -f; docker info 2>/dev/null | grep --after-context=3 "Containers"; break;;
	esac
done




