#!/bin/sh

if docker info 2>/dev/null | grep -q "Containers"; then
	echo " 🐋"
else
	echo " ❌"
fi


#case $BLOCK_BUTTON in
	 #1) setsid -f "$TERMINAL" -e "docker info 2>/dev/null | grep -A 4 "Containers" | tail -f";;
 #esac
