#!/bin/sh

opening_text="Events Today:"

today=`date +"%x"`
tomorrow=`date +"%x" -d "+1 days"`
no_events="No Events Found"

gcalcli agenda $today $tomorrow | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g; /^$/ d" > ~/.cache/gcal


events=`cat ~/.cache/gcal | wc -l`

if grep -q "$no_events" ~/.cache/gcal;
then
  echo "$opening_text 0"
elif [ "$events" > 0 ]
then
  echo "$opening_text $events"
fi

{
gcalcli calm &
gcalcli agenda $today $tomorrow
} > ~/.cache/gcal

case $BLOCK_BUTTON in
	 1) "$TERMINAL" -e tail -f -n 60 ~/.cache/gcal ;;
esac
