#!/bin/sh

speech_program=say

if ! command -v say &> /dev/null
then
    speech_program=espeak
fi


curl -s https://api.kanye.rest | awk -F: '{ print $2 }' | sed "s/}//g" | $speech_program 2>/dev/null


