#!/bin/sh

chosen=$(printf "English\\nSpanish" | dmenu -i -p "Select Language") &&

if [ "$chosen" == "English" ]; then
        setxkbmap -layout us -option caps:swapescape
elif [ "$chosen" == "Spanish" ]; then
        setxkbmap -layout es -option caps:swapescape
fi
