#!/bin/sh
intern=$(xrandr -q | grep -i "edp" | awk '{print $1}')
extern=$(xrandr -q | grep -i "\-2\-1" | awk '{print $1}')

while true
do
    if xrandr | grep "$extern disconnected"; then
        xrandr --output "$extern" --off --output "$intern" --auto
    else
        xrandr --output "$intern" --off --output "$extern" --auto
    fi
    sleep 1s
done
