#!/bin/sh

while true; do

	lid_status=$(awk '{print $2}' '/proc/acpi/button/lid/LID/state')
	hdmi_screen="HDMI1"
	laptop_screen="eDP1"


	if [[ $lid_status == "closed" ]]; then
		xrandr --output $hdmi_screen --auto --output $laptop_screen --off
		#this is for the hdmi speakers
		pactl set-card-profile 0 output:hdmi-stereo-extra1
		#this is for the lapstop speakers
 		#pactl set-card-profile 0 output:analog-stereo
	fi
done
