#!/bin/sh

common_ports='20,21,22,23,25,53,80,110,119,123,143,161,194 '

create_port_range(){
	# Highest number of ports 65535 that could be open
	arg1=$1
  seq -s, $arg1
}

echo "Enter specific IP address (192.168.1.1) or range (ex.192.168.1.0/24) you want to scan "
read ip_range

if [[ $ip_range == 192* ]]
then
	command='-sTV'
else
	command='-PnVo'
fi

echo "Do you want to scan a range of ports, common ports, specific port, or check target details?"

select answer in "range" "common" "specific" "details"; do
	case $answer in
		range ) echo "What port range do you want to use?"; read range; port_range=$(create_port_range $range); nmap $command -p $port_range $ip_range | grep "open\|report"; break;;
		common ) nmap $command -p $common_ports $ip_range | grep "open\|report"; break;;
		specific ) echo "Type a port"; read port; nmap $command -p $port $ip_range | grep "open\|report"; break;;
		details ) sudo nmap -O $ip_range; exit 1; break;;
	esac
done

if [[ $ip_range == *//* ]] || [[ $ip_range == *\/*  ]]; then
  echo "Do you want to scan one of the IP addresses for vulnerabilities"
  select answer in "yes" "No"; do
		case $answer in
			yes ) echo "Which IP do you want to scan?"; read vulnerable_ip; nmap --script vulners $command $vulnerable_ip; break;;
			no ) echo "Ok"; break;;
		esac
	done
else
  echo "Do you want to scan the IP for vulnerabilities"
  select answer in "yes" "No"; do
		case $answer in
			yes ) nmap --script vulners $command $ip_range; break;;
			no ) echo "Ok"; break;;
		esac
	done
fi
