#!/bin/sh


phone_ip=$(sudo arp-scan -l | grep 'HUAWEI' | awk '{print $1}')


if ! rsync --update --progress -e 'ssh' -Oazvrt $HOME/media/rsync/* android_phone:/mnt/ext_sdcard/rsync 2>/dev/null; then
	echo "No connection available, is the ssh client turned on? and are you connected to the lan?"
else
	echo "Files transfered"
fi
