#!/bin/sh

curl -s "https://en.wikipedia.org/wiki/List_of_UFC_events" | xpath -q -e '//table[@id="Scheduled_events"]//td' | sed "/reference/d; /<\/td>/d; /mw-redirect/d; /rowspan/d; s/<td>//g; s/<[^>]\+>/ /g" > $XDG_CACHE_HOME/ufc_events.txt

today=$(date -d $(date +"%Y%m%d") +%s)

latest_ufc_date=$(date -d $(tail -n1 $XDG_CACHE_HOME/ufc_events.txt | sed "s/,//g; s/ /-/g") +%s)


if [[ $today == $latest_ufc_date ]]; then
	difference='Today'
else
	difference=$(date --date @$(($latest_ufc_date-$today)) +'%-d days')
fi

ufc_event_name=$(tail -n2 $XDG_CACHE_HOME/ufc_events.txt | head -n1)
echo "${difference}:${ufc_event_name}"

